# Generated by Django 6.0.6 on 2026-07-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uid', models.CharField(blank=True, max_length=50)),
                ('method', models.CharField(choices=[('rfid', 'RFID Card'), ('keypad', 'Keypad PIN')], default='rfid', max_length=10)),
                ('granted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gas_leak', 'Gas Leak'), ('fire', 'Fire / Flame'), ('water_leak', 'Water Leak'), ('overcurrent', 'Current Overload'), ('intrusion', 'Motion / Intrusion'), ('window_open', 'Window / Door Open'), ('vibration', 'Vibration / Seismic'), ('rfid_denied', 'RFID Access Denied'), ('system', 'System / Hardware Fault')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
