# Generated by Django 6.0.6 on 2026-07-04 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('devices', '0002_device_device_key_device_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device'),
        ),
    ]
