# Generated by Django 6.0.6 on 2026-07-05 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_device'),
        ('devices', '0002_device_device_key_device_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='devices.device'),
        ),
    ]
