# Generated by Django 6.0.6 on 2026-07-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('anomaly_detector', 'Anomaly Detector'), ('gas_classifier', 'Gas Leak Severity Classifier'), ('seismic_classifier', 'Earthquake vs Vibration Classifier'), ('occupancy_predictor', 'Occupancy Predictor'), ('energy_forecaster', 'Energy Usage Forecaster')], max_length=30)),
                ('input_data', models.JSONField()),
                ('prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
