# Generated by Django 6.0.6 on 2026-07-04 20:14

import devices.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_key',
            field=models.CharField(default=devices.models.generate_device_key, editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.household'),
            preserve_default=False,
        ),
    ]
