# Generated by Django 6.0.6 on 2026-07-12 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_is_active'),
        ('devices', '0002_device_device_key_device_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='door_status',
            field=models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked')], default='locked', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='garage_status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('pending', 'Awaiting Confirmation')], default='vacant', max_length=10),
        ),
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_cards', to='accounts.household')),
            ],
            options={
                'unique_together': {('household', 'uid')},
            },
        ),
    ]
