# Generated by Django 6.0.6 on 2026-07-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_door_status_device_garage_status_rfidcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gate_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='garage_status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('pending', 'Awaiting Confirmation'), ('opening', 'Opening')], default='vacant', max_length=10),
        ),
    ]
