# Generated by Django 6.0.6 on 2026-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_gate_status_alter_device_garage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='automation_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
