# Generated by Django 6.0.6 on 2026-07-04 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('distance', 'Ultrasonic Distance'), ('motion', 'PIR Motion'), ('window', 'Reed Switch / Window'), ('gas', 'MQ-2 Gas'), ('flame', 'Flame Sensor'), ('water', 'Water Leak'), ('current', 'ACS712 Current'), ('light', 'LDR Light Level'), ('vibration', 'MPU6050 Vibration')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_type', 'timestamp'], name='sensors_sen_sensor__f7753b_idx'), models.Index(fields=['device', 'timestamp'], name='sensors_sen_device__a87cca_idx')],
            },
        ),
    ]
